CREATE OR REPLACE TRIGGER actualizar_inventario_venta_mueble
AFTER INSERT OR UPDATE ON DETALLE_V_MUEBLES
FOR EACH ROW
BEGIN
    UPDATE Mueble
    SET CANTIDAD = CANTIDAD - NEW.CANTIDAD
    WHERE ID_MUEBLE = NEW.ID_MUEBLE;
END;