CREATE OR REPLACE TRIGGER actualizar_inventario_compra_mueble
AFTER INSERT OR UPDATE ON DETALLE_COMPRA
FOR EACH ROW
BEGIN
    UPDATE Mueble
    SET CANTIDAD:= CANTIDAD + :NEW.CANTIDAD
    WHERE ID_MUEBLE = :NEW.ID_MUEBLE
END;
