CREATE OR REPLACE TRIGGER actualizar_inventario_muebles
AFTER INSERT OR UPDATE ON DETALLE_COMPRA
FOR EACH ROW
BEGIN
    UPDATE DETALLE_V_MUEBLES
    SET CANTIDAD:= CANTIDAD + :NEW.CANTIDAD
    WHERE ID_MUEBLE = :NEW.ID_MUEBLE
END;
