DROP TABLE SUCURSAL_TIPO_PRESTAMO;
DROP TABLE TRANSACPAGOS;
DROP TABLE PRESTAMO_CLIENTE;
DROP TABLE TELEFONO_CLIENTE;
DROP TABLE EMAIL_CLIENTES;
DROP TABLE CLIENTE;
DROP TABLE TIPO_PRESTAMO;
DROP TABLE TIPO_TELEFONO;
DROP TABLE TIPO_EMAIL;
DROP TABLE PROFESION_CLIENTE;
DROP TABLE SUCURSAL;
DROP TABLE USUARIO;

DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_EMAIL;
DROP SEQUENCE SEQ_TELEFONO;
DROP SEQUENCE SEQ_PRESTAMO;