-- Creación de tabla sucursales
CREATE TABLE SUCURSAL (
    COD_SUCURSAL NUMBER,
    NOMBRESUCURSAL VARCHAR2(50) NOT NULL,
    MONTOPRESTAMOS NUMBER NOT NULL,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_SUCURSAL)
);